version: 0.9.00.{build}

image:
- Visual Studio 2017
- Ubuntu

configuration: Release

platform:
- x64

pull_requests:
  do_not_increment_build_number: false

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
  - doc/*
  - README.md
  - .gitignore
  - LICENSE

cache:
- packages -> **\packages.config
- '%LocalAppData%\NuGet\Cache'

before_build:
- ps: |
    if ($isLinux) {
      $env:COMPILED_BY = "Mono"
      $env:EDITION = "mono"
    } else {
      $env:COMPILED_BY = "VS2017"
      $env:EDITION = "dotnet"
    }
- cmd: IF EXIST runprebuild.bat runprebuild.bat
- cmd: nuget restore Halcyon.sln

build:
  parallel: true
  verbosity: minimal
  project: Halcyon.sln
  publish_nuget: false
  publish_nuget_symbols: false

for:
-
  matrix:
    only:
    - image: Ubuntu
  build_script:
  - ./build.sh

after_build:
- ps: |
    If (Test-Path "bin/OpenSim.Framework.Servers.dll") {
      $halcyon_version = (Get-ChildItem -Path bin/OpenSim.Framework.Servers.dll | % versioninfo).ProductVersion
      Write-Output "Detected version: $halcyon_version"
      Write-Output "AppVeyor build number: $env:APPVEYOR_BUILD_NUMBER"
      $build_version = "$halcyon_version-$env:APPVEYOR_BUILD_NUMBER"
      If ("$env:APPVEYOR_BUILD_VERSION" -ne "$build_version") {
        Update-AppveyorBuild -Version "$build_version"
      }
    }
- ps: Rename-Item -Path bin -NewName halcyon-$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH-$env:EDITION

# No tests for now.
test: off

artifacts:
- path: halcyon-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(EDITION)
  name: Halcyon-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(EDITION)
  type: zip

deploy:
  provider: GitHub
  auth_token:
    secure: DlRS0U90AATbPkzxigCLwaGe1vguHFeC3a0YhMZRA/OYEbLQ8+ybp2OGfqgwpbW4
  artifact: Halcyon-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(EDITION)
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
